export const Antidepressants = {
  defaultEstablishedMeans: {
    'Amitriptyline': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Bupropion': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Citalopram': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Cyclobenzaprine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desipramine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desmethyldoxepin': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Doxepin': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Duloxetine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Fluoxetine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydroxybupropion': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Imipramine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norquetiapine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Nortriptyline': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Paroxetine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Quetiapine': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Sertraline': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Trazodone': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  defaultIstdAnalytes: {
    'IS_Amitriptyline_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Bupropion_D9': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Buspirone_D9': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Cyclobenzaprine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Desipramine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Desmethyldoxepin_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Doxepin_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Fluoxetine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydroxybupropion_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Peroxetine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Quetiapine_D8': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Sertraline_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Trazodone_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  defaultInstruments: ['LCMS 1', 'LCMS 3']
};