export const OralFluids = {
  defaultEstablishedMeans: {
    '6MAM 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Alprazolam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Amphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Benzoylecgonine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Buprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Carisoprodol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Clonazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Cocaine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Codeine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Diazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Fentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydrocodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydromorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Lorazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'MDMA 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Meprobamate 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methadone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methamphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Midazolam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Morphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Naloxone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norbuprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Nordiazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norfentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxycodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxymorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Phencyclidine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Quetiapine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Temazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'THC 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Tramadol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  defaultIstdAnalytes: {
    'IS_6MAM_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Aminoclonazepam_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Amphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Benzoylecgonine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Cocaine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Codeine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Diazepam_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Fentanyl_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydrocodone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydromorphone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methadone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methamphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Morphine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Nordiazepam_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Oxycodone_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Phencyclidine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Quetiapine_D8': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_THC_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  instruments: ['LCMS 9']
};