export const Pain2 = {
  defaultEstablishedMeans: {
    '6-MAM 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Alprazolam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Aminoclonazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Aminoflunitrazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Amitriptyline 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Amphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Benzoylecgonine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Buprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Bupropion 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Carisoprodol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Citalopram 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Clonidine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Codeine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Cotinine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Cyclobenzaprine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desipramine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desmethyldoxepin 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desmethyltapentadol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Desmethyltramadol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Dextromethorphan 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Diazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Doxepin 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'EDDP 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Fentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Fluoxetine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydrocodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydromorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydroxyalprazolam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydroxybupropion 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Imipramine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Ketamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Lorazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'MDA 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'MDEA 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'MDMA 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Meperidine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Meprobamate 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methadone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methamphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methylphenidate 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Morphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Naloxone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Naltrexone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norbuprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Nordiazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norfentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norhydrocodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norketamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Normeperidine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Noroxycodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Nortriptyline 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxycodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxymorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Phencyclidine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Ritalinic Acid 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Tapentadol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Temazepam 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Tramadol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Zaleplon 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Zolpidem 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Zolpidem Phenyl COOH 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Amobarbital 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Butalbital 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Phenobarbital 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'THC-COOH 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  defaultIstdAnalytes: {
    'IS_6MAM_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Aminoclonazepam_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Amitriptyline_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Amphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Benzoylecogonine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Bupropion_D9': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Buspirone_D8': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Codeine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Cotinine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Cyclobenzaprine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Desipramine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Desmethyldoxepin_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Diazepam_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Fentanyl_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Fluoxetine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydrcodone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydromorphone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydroxybupropion_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Ketamine_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Meperidine_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methadone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methamphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methylphenidate_D9': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Morphine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Nordiazepam_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Norketamine_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Normeperidine_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Oxycodone_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Phencyclidine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Propoxyphene_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Ritalinic_Acid_D10': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Zaleplon_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Zolpidem_D7': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Butalbital_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Pentobarbital_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Phenobarbital_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_THC-COOH_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  instruments: ['LCMS 2', 'LCMS 5', 'LCMS 6', 'LCMS 7']
};
