export const Pain3 = {
  defaultEstablishedMeans: {
    '6-MAM 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Amphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Benzoylecgonine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Buprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Carisoprodol 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Codeine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Cotinine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'EDDP 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Fentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydrocodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Hydromorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Meprobamate 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methadone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Methamphetamine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Morphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Naloxone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norbuprenorphine 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Norfentanyl 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxycodone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'Oxymorphone 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'THC-COOH 1': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
  },
  defaultIstdAnalytes: {
    'IS_6MAM_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Amphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Benzoylecogonine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Buprenorphine_D4': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Carisoprodol_D7': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Codeine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Cotinine_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_EDDP_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Fentanyl_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydrocodone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Hydromorphone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methadone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Methamphetamine_D5': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Morphine_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Oxycodone_D6': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_Oxymorphone_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },
    'IS_THC-COOH_D3': { peakArea: 1000, retentionTime: { min: 2, max: 5 } },

  },
  defaultInstruments: ['LCMS 6', 'LCMS 7']
};